config/routes.rb
Rails.application.routes.draw do
  resources :maps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  # before_save :update_lonlat
  #
  # def update_lonlat
  #   lonlat = address_to_lonlat(read_attribute(:address))
  #   write_attribute(:lonlat, lonlat)
  # end
  #
  # # 住所を保存用経緯度に変換
  # def address_to_lonlat(address)
  #   result = Geocoder.search(address)
  #   lonlat = result.first.coordinates
  #   return lonlat.join(',')
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: %i[ show edit update destroy ]

  # GET /maps or /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1 or /maps/1.json
  def show
    respond_to do |format|
      format.html
      format.js { @map }
    end
  end

  # GET /maps/new
  def new
    @map = Map.new
    @maps = Map.all
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps or /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: "Map was successfully created." }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1 or /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: "Map was successfully updated." }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1 or /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: "Map was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def map_params
      params.require(:map).permit(:name, :address, :comment, :lonlat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
  integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
  crossorigin=""/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API']%>" async defer></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
      integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
      crossorigin=""></script>
    <script src="https://unpkg.com/leaflet.gridlayer.googlemutant@latest/dist/Leaflet.GoogleMutant.js"></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.3.0/dist/leaflet.markercluster.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.3.0/dist/MarkerCluster.css" />
<link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.3.0/dist/MarkerCluster.Default.css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_with(model: @map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.hidden_field :lonlat %>
  </div>

  <div id="mapid" style="height: 500px; width: 500px;"></div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<script>
mymap = L.map('mapid').setView([35.678362, 139.715387], 16);
var gm = L.gridLayer.googleMutant({
    type: 'roadmap'
  });
gm.addTo(mymap)

var crossIcon = L.icon({ //センタークロス表示用
  iconUrl: '/target.png',
  iconSize: [32, 32],
  iconAnchor: [16, 16]
});
var crossMarker = L.marker( mymap.getCenter(),{icon:crossIcon,zIndexOffset:1000,interactive:false} ).addTo(mymap);

mymap.on('move', function(e) {
    crossMarker.setLatLng(mymap.getCenter()); //センタークロス表示用

    //マップムーブイベントで値を出力
    outputPos(mymap);

  });

// Control OSM Geocoder
// var option = {
// position: 'topright', // topright, topleft, bottomright, bottomleft
// text: '検索',
// placeholder: '検索条件を入力してください。'
// }
// var osmGeocoder = new L.Control.OSMGeocoder(option);
// gm.addControl(osmGeocoder);
  // // Plugin leaflet-fusesearch の設定
  // var searchCtrl = L.control.fuseSearch()
  // searchCtrl.addTo(map);
  //
  // // Layer control, setting
  // var layerCtrl = L.control.layers();
  // var featureLayer = L.featureGroup();
  // layerCtrl.addOverlay(featureLayer);
  // featureLayer.addTo(map);


//現在の緯度・経度・倍率を取得して指定の要素に情報を出力する関数
  function outputPos(mymap){
      var pos = mymap.getCenter();
      var zoom = mymap.getZoom();
      document.getElementById('map_lonlat').value = `${pos.lat.toFixed(6)}, ${pos.lng.toFixed(6)}`;
  }

</script>

app/views/maps/_show.html.erb
<div class="modal-wrap">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= map.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= map.address %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= map.comment %>
  </p>

  <p>
    <strong>Lonlat:</strong>
    <%= map.lonlat %>
  </p>

  <%= link_to 'Edit', edit_map_path(map) %> |
  <%= link_to 'Back', maps_path %>
</div>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Comment</th>
      <th>Lonlat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.name %></td>
        <td><%= map.address %></td>
        <td><%= map.comment %></td>
        <td><%= map.lonlat %></td>
        <td><%= link_to 'Show', map,remote:true %></td>
        <td><%= link_to 'Edit', edit_map_path(map)%></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<div id="mapid"></div>
<script>
  mymap = L.map('mapid').setView([35.678362, 139.715387], 16);
  var gm = L.gridLayer.googleMutant({
      type: 'roadmap'
    });
  gm.addTo(mymap);

  //イベント作成ページへのリンク（ポップアップ）
  var postEvent = '<%= link_to "ここにイベントを作成", new_map_path() %>';
// クリックイベント
  mymap.options.singleClickTimeout = 250;
  mymap.on('singleclick', function(ev){
    L.popup().setLatLng(ev.latlang).setContnt(postEvent).openOn(mymap);
  });

  var markers = L.markerClusterGroup();

  <% @maps.each_with_index do |map, i| %>
    var myIcon = L.icon({iconUrl: "/marker.png",iconSize:[30,30], iconAnchor:[15,15]});
    var comment = '<%= link_to map.comment, map_path(map), remote:true %>'
    var marker = L.marker("<%= map.lonlat %>".split(','), {icon: myIcon },);
    marker.bindPopup(comment);
    // marker.addTo(mymap);
    markers.addLayer(marker);
  <% end %>

  mymap.addLayer(markers);

  // mymap.on('click',function(e){
  //   lat = e.latlng.lat;
  //   lng = e.latlng.lng;
  //   eventPoint = e
  // });

  // eventPoint.bindPopup(postEvent);
</script>

<%= link_to 'New Map', new_map_path %>

<!-- モーダルの周囲を薄暗くするマスク -->
  <div id="mask" class="hidden"></div>
<!-- モーダル
あとからJavaScriptで<div>内のコードをshowビューのコードに置き換えます。 -->
  <div id="modal" class="hidden">
    <p>ここに詳細が表示される</p>
  </div>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @map.address %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @map.comment %>
</p>

<p>
  <strong>Lonlat:</strong>
  <%= @map.lonlat %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>

app/views/maps/show.js.erb
<!-- モーダルを取得 -->
var modal = document.getElementById('modal');
<!-- マスクを取得 -->
var mask = document.getElementById('mask');

<!-- モーダルの中身をshowビューに置き換えます。部分テンプレートのパス、localsの値はアプリにより異なります。 -->
modal.innerHTML = '<%= escape_javascript(render partial: 'show', locals: { map: @map}) %>';

<!-- hiddenクラスを消してモーダルとマスクを表示させます。 -->
modal.classList.remove('hidden');
mask.classList.remove('hidden');

<!-- モーダルの外側（マスク）をクリックするとhiddenクラスが書き込まれ、モーダルとマスクが再び非表示となります。 -->
mask.addEventListener('click', function(){
 modal.classList.add('hidden');
 mask.classList.add('hidden');
 });